### ISSUE TITLE
Does not work with setuptools 39.1.0

### ISSUE THREAD

**Issue by dimonji** [and800/aioreloader#7]
Task exception was never retrieved
future: <Task finished coro=<call_periodically.<locals>.wrap() done, defined at /venv/lib/python3.7/site-packages/aioreloader/_contents.py:70> exception=NotADirectoryError(20, 'Not a directory')>
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/aioreloader/_contents.py", line 74, in wrap
    yield from callback(*args, loop=loop)
  File "/venv/lib/python3.7/site-packages/aioreloader/_contents.py", line 85, in check_and_reload
    modify_times
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/venv/lib/python3.7/site-packages/aioreloader/_contents.py", line 98, in check_all
    if check(path, modify_times):
  File "/venv/lib/python3.7/site-packages/aioreloader/_contents.py", line 107, in check
    time = os.stat(target).st_mtime
NotADirectoryError: [Errno 20] Not a directory: '/venv/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py'

**Comment by and800** [comment]
Fixed in version `0.2.2`, thank you.
